### ISSUE TITLE
Does not support '.hpp' files.

### ISSUE THREAD

**Issue by UtkarshBhatthere** [cpplint/cpplint#111]
I usually code cpp headers in .hpp files., but cpplint does not accepts the file extension '.hpp' hence I have to change the name to '.h' in all occurrences  (which is tedious). I have forked cpplint and am planning to contribute to the repo, if the use of '.hpp' is not strictly disabled I'll create a PR with added acceptance.

**Comment by kuskmen** [comment]
@UtkarshBhatthere , have you come up with something? I want to try cpplint but most of my code is in hpp files so this might be the deciding point..

**Comment by UtkarshBhatthere** [comment]
Yeah, I came up with a workaround in my copy of the repo. But I guess the devels maintaining this (or the rules over which cpplint is based) are not interested in '.hpp' so even if I create a PR it won't get merged.

**Comment by UtkarshBhatthere** [comment]
Hey, I installed a cpplint through pip very recently and apparently it's accepting '.hpp' files as well. I think they resolved it. You can try it out.

**Comment by kuskmen** [comment]
Yes, I did, it works as intended.
