### ISSUE TITLE
cpplint/cpplint.py false positive error for copy constructor

### ISSUE THREAD

**Issue by netmonitoring** [cpplint/cpplint#112]
According to C++ [specification](https://en.cppreference.com/w/cpp/language/copy_constructor):
>A copy constructor of class T is a non-template constructor whose first parameter is T&‍, const T&‍, volatile T&‍, or const volatile T&‍, and either there are no other parameters, or the rest of the parameters all have default values.

The file `cpplint/cpplint.py` line number 3147 should be modified.

From: `Match(r'(const\s+)?%s(\s*<[^>]*>)?(\s+const)?\s*(?:<\w+>\s*)?&'`

To: `Match(r'((?:const|volatile|const\s+volatile|volatile\s+const)\s+)?%s(\s*<[^>]*>)?(\s+const)?\s*(?:<\w+>\s*)?&'`

To prevent false positive ccplint error:
> error cpplint: [runtime/explicit] Single-parameter constructors should be marked explicit.

When copy constructor is defined like:
`MyClass(volatile MyClass& rhs)`
`MyClass(const volatile MyClass& rhs);`
`MyClass(volatile const MyClass& rhs);`

**Comment by tkruse** [comment]
Thanks. I believe you are correct. It may be a good idea to also add an issue at upstream (https://github.com/google/styleguide/issues), even if that project may never respond to issues.

Would you like to review https://github.com/cpplint/cpplint/pull/120?

**Comment by netmonitoring** [comment]
I already added the issue to google styleguide on the same day too ([link](https://github.com/google/styleguide/issues/485)).

And your change is not the same as provided me. I am not sure your variant will work in all possible cases.

**Comment by tkruse** [comment]
I added testcases, I think for all combinations included in your regex. Do you have any additional testcase in mind?
