### ISSUE TITLE
--exclude not work on Windows with cpplint 1.4.4 Python 3.7.3

### ISSUE THREAD

**Issue by universeroc** [cpplint/cpplint#114]
I'm trying to use cpplint for code static analysis and here I'm in the trouble with excluded directories :(

Long time ago I used a batch script to list all directory and files into a file list and feed cpplint to get the results, but there's distadvantages that when the files it too many it'll overflow the max length of command line to work.

I've already try to use all the follow code, but none works:

```
cpplint --root=src --filter=-build/include_subdir,-build/c++11 --repository=src --recursive  --exclude=src/third_party/* src
```

```
cpplint --root=src --filter=-build/include_subdir,-build/c++11 --repository=src --recursive  --exclude=src/third_party/*/* src
```

```
cpplint --root=src --filter=-build/include_subdir,-build/c++11 --repository=src --recursive  --exclude=src/third_party/*/* --exclude=src/third_party/* --exclude=src/third_party/*/*/* src
```

cpplint always lint the very `src/third_party` directory, please help me, I'm struggling with this issue about several weeks. Hopeless :(

Remark:

cpplint is installed by:

```
pip install cpplint
```

**Comment by GrueMaster** [comment]
This appears to also affect Linux (Ubuntu 16.04).  Installed with pip3 install cpplint.  Trying to use '--exclude=thirdparty/*' (where we pull in googletest as a submodule as it fails - go figure).  Tried multiple regex patterns to exclude that path.

**Comment by universeroc** [comment]
> This appears to also affect Linux (Ubuntu 16.04). Installed with pip3 install cpplint. Trying to use '--exclude=thirdparty/*' (where we pull in googletest as a submodule as it fails - go figure). Tried multiple regex patterns to exclude that path.

Thank you for your reply, I'll try this way to check it :)

**Comment by universeroc** [comment]
@GrueMaster Sorry to tell the result: pip is the pip3 on my PC as there's only Python3 installed on my device. Any advice for this problem?

**Comment by GrueMaster** [comment]
I was only listing how I installed it.  Ubuntu 16.04 has both Python2.7 (pip) and Python 3.5 (pip3).  

I have a fix for this issue in my own branch, download and try it.  I filed a pull request as well.

**Comment by universeroc** [comment]
> I was only listing how I installed it. Ubuntu 16.04 has both Python2.7 (pip) and Python 3.5 (pip3).
> 
> I have a fix for this issue in my own branch, download and try it. I filed a pull request as well.

I've checked your code, and run on my folder, but it not works also :(

Maybe official patch should be applied

**Comment by universeroc** [comment]
> I was only listing how I installed it. Ubuntu 16.04 has both Python2.7 (pip) and Python 3.5 (pip3).
> 
> I have a fix for this issue in my own branch, download and try it. I filed a pull request as well.

OK, I've tried your patch locally, and find that `value` must use "" to sround or it failed

```
cpplint --exclude="third_party/*" src
```

**Comment by GrueMaster** [comment]
> OK, I've tried your patch locally, and find that value must use "" to sround or it failed

If you are running from the shell, then yes you need to surround the "*" with quotes.  Otherwise the shell will try to expand on it before passing it to the application.  If you are running from some other app (we use Jenkins), then this is not necessary.  For example, in a Makefile where it is called directly.

**Comment by universeroc** [comment]
> > OK, I've tried your patch locally, and find that value must use "" to sround or it failed
> 
> If you are running from the shell, then yes you need to surround the "*" with quotes. Otherwise the shell will try to expand on it before passing it to the application. If you are running from some other app (we use Jenkins), then this is not necessary. For example, in a Makefile where it is called directly.

Yes, you're right. Thank you for your patch

**Comment by tkruse** [comment]
Using Python>=3.5, I believe `--exclude="third_party/**/*"` might work.

**Comment by universeroc** [comment]
> Using Python>=3.5, I believe `--exclude="third_party/**/*"` might work.

Sorry, see my title it's already Python 3.7.3 but it did not work
