### ISSUE TITLE
Does cpplint have a config file?

### ISSUE THREAD

**Issue by cclauss** [cpplint/cpplint#118]
Does cpplint read a __.cpplint__ or other config file?
Like https://github.com/nodejs/node/blob/master/.cpplint

**Comment by tkruse** [comment]
It supports a file called CPPLINT.cfg, see https://github.com/cpplint/cpplint/blob/4f2119f3402b91c9a97dc247191129b14d246b8a/cpplint.py#L222, and also the implementation at https://github.com/cpplint/cpplint/blob/1.4.4/cpplint.py#L222. (documentation about it could be better).

Closing this issue as it seems like a yes/no question.
