### ISSUE TITLE
Are `Google C++ Style Guide` rules all implemented in cpplint?

### ISSUE THREAD

**Issue by llht** [cpplint/cpplint#132]
I see rules like `General Naming Rules` or `Variable Names` not show when I run `cpplint file.c`.

**Comment by tkruse** [comment]
The error categories are listed in the source file: https://github.com/cpplint/cpplint/blob/851ceb00cba6301b00167cf5c313532bc05cf1eb/cpplint.py#L270

Not sure if that answers your question.

**Comment by llht** [comment]
@tkruse Thank you very much. This helps a lot!!

**Comment by sinamr** [comment]
Hi, 

Actually, I have the same concern as the `General Naming Rules` seems to not have been implemented. Am I right or I need to add a specific filter to make it work?

Best, 
Sina
