### ISSUE TITLE
NOLINT(category) for whole file

### ISSUE THREAD

**Issue by NINI1988** [cpplint/cpplint#137]
I have a generated file which has too long lines.

It would be great if it would be possible to ignore line lengths for the whole file instead of every line.
Eg: NOLINTFILE(whitespace/line_length).

Or is there another way to ignore the line lengths for a specific file?

**Comment by tkruse** [comment]
Hi,
sorry, I don't think there is such a feature in cpplint right now, though for some categories, the NOLINT directive has a global effect, see `ProcessGlobalSuppresions()`. But not for line length.

Given your file is generated, what benefit do you get from running cpplint on it?

**Comment by tkruse** [comment]
Note it's possible to put the file in a separate folder and configure filters for the folder using a `CPPLINT.cfg` file
