### ISSUE TITLE
Support relative include path `#include "./header.h"`

### ISSUE THREAD

**Issue by ngolin** [cpplint/cpplint#139]
There is a "build/include_subdir" warning for `#include "header.h"`.

But the followings are very clean and clear, we should be fine with them:
- `#include "./header.h"`
- `#include "../include/header.h"`

Thank you.

**Comment by tkruse** [comment]
Hi, thanks for the suggestion. Cpplint follows the Google Styleguide, which says 

> All of a project's header files should be listed as descendants of the project's source directory without use of UNIX directory aliases . (the current directory) or .. (the parent directory). 
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

I cannot explain the downsides of using Unix directory aliases, maybe it's just for consistency. So it's unlikely cpplint can add this change unless it's a major problem or is changed in the upstream repository https://github.com/google/styleguide

**Comment by jameslamb** [comment]
I faced this issue tonight in the CI for a project and it took a bit of time to figure out what was going on.

Currently, the warning you get if you use `#include "./something.h"` in `something.cpp` is:

> src/something.cpp:2:  src/something.cpp should include its header file src/something.h  [build/include] [5]

If `./` is not allowed per the Google style guide, could a more informative warning be generated?

Like: 

> use of UNIX directory aliases like '.' and '..' is not allowed in include statements"

**Comment by tkruse** [comment]
Extending the error message sounds like a nice improvement, yes.
