### ISSUE TITLE
Add Pre-Commit Hooks

### ISSUE THREAD

**Issue by OlehKSS** [cpplint/cpplint#165]
I wanted to configure your package to use it with [pre-commit](https://pre-commit.com/) on Linux.
As I see it doesn't have a default pre-commit hook.
It would be nice to have it since this tool looks really useful.

The main tasks as I see:
- [ ] add `.pre-commit-config.yaml` containing default configurations
- [ ] add a reference to `cpplint` to the list of [supported hooks](https://pre-commit.com/hooks.html)

**Comment by MarcoGorelli** [comment]
the first task should be to add `.pre-commit-hooks.yaml` - agreed that this would be useful, would a PR be welcome?

**Comment by tkruse** [comment]
Hi, I am not familiar with pre-commit. It seems to me that on the supported hooks page, there are already at least 2 existing repos with configuration for cpplint. I am fine with merging a yaml file MR, along with a small addition to the README on how to use with pre-commit.

**Comment by tkruse** [comment]
But PR is welcome, yes

**Comment by MarcoGorelli** [comment]
> there are already at least 2 existing repos with configuration for cpplint.

true, but the advantage of having a hook here is that if you release a new version, then `pre-commit autoupdate` will update to it automatically

**Comment by OlehKSS** [comment]
An update to the list of [supported hooks](https://pre-commit.com/hooks.html) will be added [here](https://github.com/pre-commit/pre-commit.com/pull/465)
