### ISSUE TITLE
[feature] Provide line-specific NOLINT per command line

### ISSUE THREAD

**Issue by PhilLab** [cpplint/cpplint#170]
In addition to the `// NOLINT` in-line suppression, also allow to suppress specific lines via the command line interface.

Of course, in-line suppression is a neat thing but there are scenarios where one would not want to modify the source files but instead store all suppressions in a more global place.

### Comparison to Cppcheck

Cppcheck for example allows this like this (see https://linux.die.net/man/1/cppcheck):
> **--suppress=spec**
>
>    Suppress a specific warning. The format of <spec> is: [error id]:[filename]:[line]. The [filename] and [line] are optional. [error id] may be * to suppress all warnings (for a specified file or files). [filename] may contain the wildcard characters * or ?. 

Cppcheck examples:
- `--suppress=knownConditionTrueFalse:myFile.cpp:64`
- `--suppress=*:myOtherFile.cpp`

### In Cpplint
- Either extend the `--exclude` syntax or add a new `--suppress` parameter behaving like cppcheck.
- This would then also allow https://github.com/cpplint/cpplint/issues/137

Without knowing the inner workings of cpplint in detail, it seems like the CLI could add additional entries to `_error_suppressions` like it is done e.g. in `ParseNolintSuppressions()`

**Comment by tkruse** [comment]
Hi, so suppression by line seems a rather niche feature to me, that is clumsy because all line numbers need to be updated when the file changes. While cppcheck may have such a feature, I am not convinced that it is a feature that is used a lot. I am reluctant to extend the feature set of cpplint to niche features when there is no reliable support community for cpplint. Though if enough people voted on this feature being included, I could be swayed.

**Comment by PhilLab** [comment]
@tkruse Thanks for responding and taking a look at the PR and this ticket.

I will try to collect the reasons why I think this is valuable and not that niche. I will separate the arguments for the file-specific suppression and the line-specific suppression. Both are possible with #171 but arguing for the former is easier than for the latter.

# A general argument for the CLI parameter
You might ask why we need this as a CLI parameter and cannot use inline-suppression via comments in every scenario. After all, as you said, suppressions need to be updated when the code changes. The main use case is to disable linting for code files you don't have the full control over. E.g. third party code you have checked-in as code files. There, you can't suppress via code comments because you don't want to touch the library's code.

It might also be that you have specific example code in your repository where you show the reader how to use your stuff. There, you might want to be less strict about *some* code smells in order to not confuse the reader. To be honest, my need arose from the fact that I am writing a programing tutorial for beginners where I a) want to lint my code so I reduce blunders but b) cannot start with the full enforcement of all style rules from the beginning. Does not make sense to teach Hello World stuff while already complaining about const correctness or references. And in later examples, I specifically violate the style in some lines to illustrate the resulting dangers.

# Suppressing a whole file
- Requested by #137.
- Crafting multiple lint calls to exclude all but a handful of files is difficult and error-prone IMHO. Defining "lint the whole folder but I give you three files to ignore" is more explicit and makes the intent clearer.
- As already mentioned, the file might be a third-party file or (as in #137) a auto-generated one .

# Suppressing specific lines
- Cppcheck offers this as well via their `--suppress` CLI parameter. The tool itself is heavily used though I admit not knowing how many use the line-specific suppression.
- Adopting its syntax because developers might already know and use cppcheck in their toolset.
- You want to disable linting for third party code you don't have control over. However, you might want to do it "opt-in" for some categories you consider critical. E.g. acknowledging each occurrence of `runtime/threadsafe_fn` or `runtime/invalid_increment` before you check in a new version of the third party library. Again, you don't want to modify the original file so you can't use inline suppression.
- (Not a particularly strong argument:) After file-specific suppression was implemented, adding line-specific was easy

**Comment by tkruse** [comment]
Thanks for writing this up. It does not convince me, but I am happy to check again after some time to see if there are upvotes.

Some problems I still see: 
* cpplint already has filter and exclusion on directory level via a `CPPLINT.cfg`. This kind-of allows to handle similar cases as intended by #137 by just placing special files in special folders (such as auto-generated files or files from a 3rd party source). Which is also a better practice than mixing them with other source code. Such a configuration file seems generally a much nicer place to add very complex filters such as per-line-per-file filters than to add this to the CLI command, in particular to avoid the situation where the cpplint command grows linearly with the source code. So for any such feature, even if I was inclined to add it, I would go for the configuration file approach first, and the CLI approach maybe second (just for easier exploration).
* I would generally recommend any team in the world which has to include 3rd-party source code in their own sources without being able to trust that code the same way the team would trust binary libraries, to use comments and suppression filters inside that copied file. Various tools exist to make it easier to maintain own downstream versions of such files, and it will make it also much easier to add comments on each suppression to explain why it's accepted.

I understand the tutorial code use-case, I had a similar issue when I tried applying cpplint to how-not-to-code samples from https://github.com/isocpp/CppCoreGuidelines. But this is a niche use-case.

Still as I said, I am happy to wait for other votes or comments.
