### ISSUE TITLE
ignoring NOLINT* comments with categories defined in other tools

### ISSUE THREAD

**Issue by wjwwood** [cpplint/cpplint#184]
If you use this tool and a tool like clang-tidy on your code base and want to suppress both, it can be an issue as it will trigger the `readability/nolint` warning from this tool, e.g.:

```c
va_copy(args_clone, *args);  // NOLINT(clang-analyzer-valist.Uninitialized)
```

Will produce a warning like this from `cpplint.py`:

```
<...>/logging.c:196:  Unknown NOLINT error category: clang-analyzer-valist.Uninitialized  [readability/nolint] [5]
```

Is there a recommended way to avoid this without completely disabling `[readability/nolint]`?

One idea I had was too maintain a list of prefixes that could be ignored, e.g. ignore all NOLINT comments with categories that start with `clang-analyzer` as an example. This list could be hard coded or could be provided by the user. Is that something that would be desired as a pull request to this repository?

**Comment by tkruse** [comment]
Hi William,
I am not aware of a better solution to the NOLINT warning.
As per the CONTRIBUTING doc, I think such any change to make cpplint more compatible with other tools would be reasonable to include.

Whether this specific one is valuable enough to put effort into it I cannot say, but I would be happy to merge such a change.

**Comment by wjwwood** [comment]
@tkruse thanks for the feedback.

I finally got around to open a pull request for this, see: https://github.com/cpplint/cpplint/pull/196

**Comment by tkruse** [comment]
Release with 1.6.1
