### ISSUE TITLE
Could you provide a cmake demo with cpplint?

### ISSUE THREAD

**Issue by nickhuangxinyu** [cpplint/cpplint#185]
I am trying to use cpplint in my cmake project.

I checked almost everything on google, but did not find a demo for use cpplint in cmake.

Can you provide a simple one?

**Comment by gohar94** [comment]
Install `cpplint` as follows:
```
pip install cpplint
```

Add it to your `CMakeLists.txt` file as follows:
```
set(CMAKE_CXX_CPPLINT "cpplint")
```
