### ISSUE TITLE
How to stop complier if cpplint has error?

### ISSUE THREAD

**Issue by nickhuangxinyu** [cpplint/cpplint#187]
I want to generate binary file only when no cpplint error existed.

I think the default behavior is just to check once, even cpplint found error, it can make out.

And next make, those error wont show again.

Can I make cpplint check a hard check, stop generate binary file and print out message everytime?

**Comment by szaszm** [comment]
cpplint doesn't integrate with compilers that closely as far as I know (maintainers please correct me if I'm wrong), so you will have to do that in your build system.

In a simple case, instead of running 
```
gcc -o output source.cpp
cpplint source.cpp
```

try

```
cpplint source.cpp && gcc -o output source.cpp
```

this way the shell only launches the compiler if the linter exited without an error.

**Comment by Mirasire** [comment]
maybe you can write a **bash script** by using `grep` and `$?` ?

here is an example:
```bash
#!/bin/bash

file="cpp_checklog"
cpplint souce.cpp >> $file | cat $file | grep errors 

if (( $? != 0 ));then
  cat $file
  exit
else;
  # gcc ...
fi
```
if you want to check all source file, you can use `find` in shell to expand it?
