### ISSUE TITLE
This environment is externally managed

### ISSUE THREAD

**Issue by melroy89** [cpplint/cpplint#236]
When running your install guide in your README under Debian Bookworm, I get:

```bash
pip3 install cpplint:
0.933 error: externally-managed-environment
0.933 
0.933 × This environment is externally managed
0.933 ╰─> To install Python packages system-wide, try apt install
0.933     python3-xyz, where xyz is the package you are trying to
0.933     install.
```

Should we update the readme?

Debian has adopted: https://peps.python.org/pep-0668/

**Comment by melroy89** [comment]
Should we aim for Python venv or `--break-system-packages`?

**Comment by ecepy0** [comment]
> Should we aim for Python venv or `--break-system-packages`?

break-system-packages didn't work for me, then i tried python venv but result was same 
i will give a second chance to venv today,what about you?

**Comment by ecepy0** [comment]
> Should we aim for Python venv or `--break-system-packages`?

`--break-system-packages` didn't work for me, then i tried python venv but result was same 
i will give a second chance to venv today, what about you?

**Comment by aaronliu0130** [comment]
[Cpplint is in Debian already.](https://packages.debian.org/bookworm/cpplint) Just do `sudo apt install cpplint`

**Comment by melroy89** [comment]
Then update the Readme.

**Comment by aaronliu0130** [comment]
#263 was way ahead of ya.
