### ISSUE TITLE
Permissions changed on cpplint.py

### ISSUE THREAD

**Issue by cvvergara** [cpplint/cpplint#240]
Hello 
I was running [this script](https://github.com/pgRouting/pgrouting/blob/main/tools/scripts/code_checker.sh)
on our CI and it was all well until recently

This from last week run was successful:
https://github.com/pgRouting/pgrouting/actions/runs/7657815725

and 2 days ago it started to have problems
https://github.com/pgRouting/pgrouting/actions/runs/7716357654

```
Run ls code_linter
cpplint
--------------------
------   *.c  ------
--------------------
./tools/scripts/code_checker.sh: line 51: code_linter/cpplint/cpplint.py: Permission denied
Error: Process completed with exit code 126.
```

Running the script and installing
```
ls -la code_linter/cpplint/*.py
-rwxrwxr-x 1 vicky vicky   8325 feb  1 09:06 code_linter/cpplint/cpplint_clitest.py
-rw-rw-r-- 1 vicky vicky 262787 feb  1 09:06 code_linter/cpplint/cpplint.py
-rwxrwxr-x 1 vicky vicky 269028 feb  1 09:06 code_linter/cpplint/cpplint_unittest.py
-rwxrwxr-x 1 vicky vicky   3081 feb  1 09:06 code_linter/cpplint/setup.py
````
`code_linter/cpplint/cpplint.py` is the only one without `x` permissions

**Comment by aaronliu0130** [comment]
I’ll check if GitHub preserves permissions metadata.

**Comment by cvvergara** [comment]
In this [run](https://github.com/cvvergara/pgrouting/actions/runs/7743543750/job/21115203225) I am using tag 1.6.1 and it runs ok

https://github.com/cvvergara/pgrouting/actions/runs/7743543750

**Comment by cvvergara** [comment]
This are the permissions on 1.6.1
```
ls -la code_linter/cpplint/*.py
-rwxrwxr-x 1 vicky vicky   8070 feb  1 09:24 code_linter/cpplint/cpplint_clitest.py
-rwxrwxr-x 1 vicky vicky 262964 feb  1 09:24 code_linter/cpplint/cpplint.py
-rwxrwxr-x 1 vicky vicky 267055 feb  1 09:24 code_linter/cpplint/cpplint_unittest.py
-rwxrwxr-x 1 vicky vicky   2960 feb  1 09:24 code_linter/cpplint/setup.py
```

**Comment by aaronliu0130** [comment]
Should work now
```ls
-rwxr-xr-x  1 aaron aaron 261977 Feb  1 16:50 cpplint.py
```
