### ISSUE TITLE
Cache cppvar

### ISSUE THREAD

**Issue by matyalatte** [cpplint/cpplint#281]
I noticed that cpplint calls `GetHeaderGuardCPPVariable(filename)` for each line. I believe cpplint should call it only once per file.

I removed the redundant function calls from [my c++ implementation of cpplint](https://github.com/matyalatte/cpplint-cpp), which reduced execution time by about 10%.

I think it's worth trying a similar optimization with cpplint.py.

**Comment by aaronliu0130** [comment]
Cool project you've got there!

Yeah, that's a great point.
