### ISSUE TITLE
Feature: Check that case of included file matches case of the filename

### ISSUE THREAD

**Issue by mdeweerd** [cpplint/cpplint#284]
Apparently cpplint does not verify that the casing of the filename mentionned in the #include matches the actual filename on disk.

While setting up a ci environment compilation failed because "Ykeypad.h" could not be found - the file is actually called "YKeypad.h" and this was undetected by cpplint.

It looks like a good addition to the ruleset.

Cpplint fork (https://github.com/cpplint/cpplint)
cpplint 1.6.1
Python 3.12.5 (main, Aug 13 2024, 01:30:38) [GCC 12.2.0]

Cpplint fork (https://github.com/cpplint/cpplint)
cpplint 1.6.1
Python 3.9.16 (main, Mar  8 2023, 22:47:22) 
[GCC 11.3.0]

**Comment by aaronliu0130** [comment]
We're not a language server. You should use something like clangd to check possible C++ errors and warnings.
