### ISSUE TITLE
IWYU - functionality removed

### ISSUE THREAD

**Issue by snirlugassy-imagry** [cpplint/cpplint#301]
I see that in PR: https://github.com/cpplint/cpplint/pull/94 the header matching functionality was removed.

This means that you have to IWYU both in the .cpp files and headers (header is not enough).
AFAIK header include should be enough for IWYU in the cpp files.

Is that a bug or a feature (style changes)?

**Comment by BartolomeyKant** [comment]
I am also wondering do I need to include, for example, \<vector\> twice in header and in source files?

**Comment by aaronliu0130** [comment]
Yes, this is a feature. See #218.
