### ISSUE TITLE
Move project to cpplint/cpplint

### ISSUE THREAD

**Issue by mattyclarkson** [cpplint/cpplint#31]
If we move the project to a organisation we can have multiple collaborators on the project and share the maintenance. We use this version of `cpplint` internally at work and would happily spend time maintaining the project, issues and PRs.

**Comment by thomasjo** [comment]
Seconded!

**Comment by tkruse** [comment]
So I for one am happy to add @mattyclarkson to the pypi list of people with rights to make releases. 
Not sure if @theandrewdavis is very active right now, he might be inclined to just pass on the baton.
We can wait a couple of days for him to reply (ping again if I forget).

An independent github organisation might be overkill for now. My personal vision is for this to remain a close siamese twin of the google upstream, only adding Python3 compatibility and very tiny changes.
For that scope, I think a github organization feels too "big".
However, if @mattyclarkson becomes main maintainer, he is free to decide such matters as well.

**Comment by mattyclarkson** [comment]
@tkruse, I think it makes the project _feel_ more of a community project rather than one persons project. I don't particularly want to be the sole maintainer but am happy to share the load with a few maintainers. I will generally be available to work on this though as we use it at work.

I agree that we should keep it close to the upstream `cpplint` as possible :+1:

**Comment by theandrewdavis** [comment]
@tkruse is right -- I'm no longer using cpplint at work so I haven't had the motivation to work on it. Would be great if you'd like to take over, @mattyclarkson.

If you'll let me know what your username on pypi is, I'll add you as an owner. And I will theandrewdavis/cpplint to point to wherever y'all decide cpplint should live (cpplint/cpplint or mattyclarkson/cpplint)

**Comment by mattyclarkson** [comment]
@theandrewdavis, my user name on PyPi is `mattyclarkson`. I would prefer if the project moved to `cpplint/cpplint` so that if the maintainer needs to change again we can just add/remove people from the organisation. I've never moved a personal project to an organisation but when we [did it](https://github.com/civetweb/civetweb/issues/183) with `civetweb/civetweb` the owner of that just got in contact with the GitHub support people I think. Having an organisation makes it easier to share the Travis permissions. S'up to you guys though, really.

I'm happy to keep maintaining it whilst we use it at work. Would be nice if a few of you are around to bounce ideas/PRs off.

**Comment by thomasjo** [comment]
@mattyclarkson No need to involve GitHub staff.

Create the organization, then give @theandrewdavis admin privileges in the organization. He can then trivially transfer the repo to the organization via _The Danger Zone™_ options,

<img width="745" alt="options" src="https://cloud.githubusercontent.com/assets/3622/19965420/30d8aa8c-a1c7-11e6-852c-b247c3a4b5a8.png">

**Comment by thomasjo** [comment]
Full details can be found here:
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by mattyclarkson** [comment]
OK have made the organisation. https://github.com/cpplint

How should be part of the organisation team?

**Comment by theandrewdavis** [comment]
That was simple enough. You're on the pypi now, @mattyclarkson, and the repo is transferred.

**Comment by mattyclarkson** [comment]
Rock on :metal:
