### ISSUE TITLE
ignore line

### ISSUE THREAD

**Issue by Drapegnik** [cpplint/cpplint#35]
Are any possibility to ignore checking line in code, like in [eslint](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) or [jshint](http://jshint.com/docs/):

```
some code \\ ccplint-ignore-line [... rules]
```

**Comment by dnfield** [comment]
For anyone else who gets here looking for how to do this, it's `// NOLINT`.

**Comment by mcandre** [comment]
NOLINT is too generic; That would disable checks from other rules and even other linters.
