### ISSUE TITLE
Order of includes error for 3rd party libraries (reopened)

### ISSUE THREAD

**Issue by m3m0ryh0l3** [cpplint/cpplint#43]
(reopening issue #7 because it was closed without resolution)
The following example snippet produces "Found C system header after C++ system header...[build/include_order]".

```cpp
#include <vector>

#include <gtest/gtest.h>
```
The problem goes away if the angle brackets are replaced by quotes.
I guess the script assumes the angle brackets only for C/C++ system and standard library headers.

I think the *CORRECT* behavior would be to encode into cpplint the full list of C system and standard-library headers (as is done with C++ standard headers).

Here's a suggested starting place:

- The system C headers (per https://en.cppreference.com/w/c/header):
  - assert.h
  - complex.h
  - ctype.h
  - errno.h
  - fenv.h
  - float.h
  - inttypes.h
  - iso646.h
  - limits.h
  - locale.h
  - math.h
  - setjmp.h
  - signal.h
  - stdalign.h
  - stdarg.h
  - stdatomic.h
  - stdbool.h
  - stddef.h
  - stdint.h
  - stdio.h
  - stdlib.h
  - stdnoreturn.h
  - string.h
  - tgmath.h
  - threads.h
  - time.h
  - uchar.h
  - wchar.h
  - wctype.h
- POSIX C headers (per http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/contents.html)
  - aio.h
  - arpa/inet.h
  - cpio.h
  - dirent.h
  - dlfcn.h
  - fcntl.h
  - fmtmsg.h
  - fnmatch.h
  - ftw.h
  - glob.h
  - grp.h
  - iconv.h
  - langinfo.h
  - libgen.h
  - monetary.h
  - mqueue.h
  - ndbm.h
  - net/if.h
  - netdb.h
  - netinet/in.h
  - netinet/tcp.h
  - nl_types.h
  - poll.h
  - pthread.h
  - pwd.h
  - regex.h
  - sched.h
  - search.h
  - semaphore.h
  - setjmp.h
  - signal.h
  - spawn.h
  - strings.h
  - stropts.h
  - syslog.h
  - tar.h
  - termios.h
  - trace.h
  - ulimit.h
  - unistd.h
  - utime.h
  - utmpx.h
  - wordexp.h
- GNUlib Headers
  - a.out.h
  - aliases.h
  - alloca.h
  - ar.h
  - argp.h
  - argz.h
  - byteswap.h
  - crypt.h
  - endian.h
  - envz.h
  - err.h
  - error.h
  - execinfo.h
  - fpu_control.h
  - fstab.h
  - fts.h
  - getopt.h
  - gshadow.h
  - ieee754.h
  - ifaddrs.h
  - libintl.h
  - mcheck.h
  - mntent.h
  - obstack.h
  - paths.h
  - printf.h
  - pty.h
  - resolv.h
  - shadow.h
  - sysexits.h
  - ttyent.h
- Other system-specific C headers
  - sys/*.h
- Hardware-specific C system headers
  - arm_neon.h
  - emmintrin.h
  - xmmintrin.h

**Comment by StrikerRUS** [comment]
Hi! Faced the same problem :-(
Is there any workaround so far?

Also, I wonder what's the maintainers'  opinion, because this's quite old and critical issue.

**Comment by tkruse** [comment]
As far as I understand the suggestion, it would only reduce false positives, and in that case the suggestion is good and such a change should be merged. I don't know when I'll have time to look into the details though.

I would generally feel more comfortable if the change was done and accepted in upstream (https://github.com/google/styleguide), though I know that project is not very responsive to change suggestions (unless they affect internal google projects).

The more people comment positively on this here, the better.

**Comment by tkruse** [comment]
Fixed with #133 (though I might revert and reopen soon)

**Comment by tkruse** [comment]
So as mentioned in the other thread, it seems google is aware of the mismatch between file type and the cpplint, e.g. per the fuchsia style guide https://fuchsia.googlesource.com/fuchsia/+/master/docs/development/languages/c-cpp/cpp-style.md :

> If the header being included is a system, global, or library header (see Naming C/C++ objects for precise definitions), use and the complete name of the header. These headers are considered “C library headers” for the purposes of the Google C++ Style Guide:

So basically even though "gtest/gtest.h" is not a C system header, it may still considered as such by Googles styleguide, as the lesser of 2 evils (having to find agood way to distinguish else).
So another fix for this issue may be to just improve the cpplint warning message like:

   "Found C-style system header include after C++-style system header include..."

Or some other way to name angle-bracket-with-extension style includes from angle-bracket-without-extension includes
