### ISSUE TITLE
Header guard warning when using pragma once.

### ISSUE THREAD

**Issue by Kyle-Thompson** [cpplint/cpplint#65]
I'm working in a codebase that occasionally uses `#pragma once` instead of a standard include guard. cpplint doesn't like this though and complains about a lack of include guard when there effectively is one. How do I get around this?

**Comment by kelson42** [comment]
Any chance this could be implemented? CodeFactor wrongly reports because of this limitation.

**Comment by tkruse** [comment]
@kelson42 : Can you provide some code sample and the error message from cpplint? I don't know yet if this is easy to implement.

**Comment by kelson42** [comment]
@tkruse See the Codefactor output int the cited PR for example. Direct link here https://www.codefactor.io/repository/github/openzim/node-libzim/pull/72

**Comment by jakoch** [comment]
The readme states `Support #pragma once as an alternative to header include guards`. 
True/False?
Where is this documented?

**Comment by aaronliu0130** [comment]
This was supposed to be added in 0.0.8. It is indeed implemented on [line 2506](https://github.com/cpplint/cpplint/blob/develop/cpplint.py#L2506), which also works on my machine. @Kyle-Thompson Could you show example of code that gets a false positive?

**Comment by Kyle-Thompson** [comment]
If it works for you I'd say this is probably fine to close. I opened this 6 years ago and then promptly forgot about it. I don't have an example of this anymore.
