### ISSUE TITLE
cpplint license "Freely Distributable"

### ISSUE THREAD

**Issue by jayvdb** [cpplint/cpplint#82]
The cpplint setup.py uses classifier "Freely Distributable", but provides no license.

As a result the distributed pacakge info is:

```
PKG-INFO:License: UNKNOWN
```

cpplint should use an SPDX compatible license.

**Comment by tkruse** [comment]
I added BSD-3-clause id to setup.py, which I believe is what Google is using.

**Comment by jayvdb** [comment]
The license file also needs to be distributed with the software, at least in the sdist.  Sorry for all the hassles, and much appreciation for getting the tests working in https://github.com/cpplint/cpplint/issues/79.

**Comment by tkruse** [comment]
LICENSE included in 1.4.2
