### ISSUE TITLE
spurious "should include its header file"

### ISSUE THREAD

**Issue by davidnixon** [cpplint/cpplint#95]
If "Foo.h" exist and you have a file like this name Foo.cc
```c++
#include "Foo.h"
```
There is an error like this:
```
 ... Foo.cc should include its header file src/Foo.h  [build/include] [5]
```

This is because "Foo.h" is excluded from the `include_state` since it matches `_THIRD_PARTY_HEADERS_PATTERN`
In this case it should not be excluded because we are checking "Foo.cc".

```sh
gunzip fix-spurious-should-include-its-header-file.patch.gz
git apply fix-spurious-should-include-its-header-file.patch
```
[fix-spurious-should-include-its-header-file.patch.gz](https://github.com/cpplint/cpplint/files/2972639/fix-spurious-should-include-its-header-file.patch.gz)

patch tested with 1e7ecd3e18674784cdad34918b14d7f178bb81e7

**Comment by tkruse** [comment]
Opened MR with patch contents at https://github.com/cpplint/cpplint/pull/96, let's discuss there, where the patch contents are also easily visible.
